### ISSUE TITLE
cssUrl not working

### ISSUE THREAD

**Issue by delcacho** [printdotio/pio.js#102]
I am trying to hide some elements from the widget.

Currently configuring as seen here:
PIO.config({
    recipeId:"70407514-d496-4697-ab82-c4c6c4810809",
    style:{
        showHeader:false,
        cssUrl:'http://www.delcacho.com/mugical/style.css'
    },
    url:"http://widget.print.io/widget/"
});

However, the CSS file is not being loaded, I have inspected with Firebug and there is no apparent change in the DOM. Full example at:
http://www.delcacho.com/mugical/test.html

**Comment by micahasmith** [comment]
![image](https://cloud.githubusercontent.com/assets/959902/10912713/ac1f93ce-8218-11e5-8afe-5b56d9dc759b.png)

switch to https

**Comment by delcacho** [comment]
Thank you. That did the trick.

On Tue, Nov 3, 2015 at 4:50 PM, Micah Smith notifications@github.com
wrote:

> [image: image]
> https://cloud.githubusercontent.com/assets/959902/10912713/ac1f93ce-8218-11e5-8afe-5b56d9dc759b.png
> 
> switch to https
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/printdotio/pio.js/issues/102#issuecomment-153395298.

## 

Carlos del Cacho

The purpose of studying economics is not to acquire a set of ready-made
answers to economic questions, but to learn how to avoid being deceived by
economists.

Joan Robinson http://en.wikipedia.org/wiki/Joan_Robinson
