### ISSUE TITLE
Moving picture after zoom

### ISSUE THREAD

**Issue by gershonungar** [printdotio/pio.js#103]
Would it be possible to let the user move the picture after they use the zoom option (let's say its a full body shot and someone wants just the face on a phone cover etc. and after zoom only the stomach is visible)

**Comment by micahasmith** [comment]
@gershonungar the "click and drag" move isnt working for you? what browser are you on?

**Comment by gershonungar** [comment]
Sorry that seems to work already. However putting multiple pictures on each page in a photobook is still not an (necessary) option. Is that a possibility?

**Comment by micahasmith** [comment]
coming soon ->

**Comment by gershonungar** [comment]
Also after picture selection the continue button doesn't seem to be working.

**Comment by micahasmith** [comment]
if you're on a photobook then you probably need to do remaining pages

**Comment by gershonungar** [comment]
no even on the phonecase right after picture selection before customization.

**Comment by gershonungar** [comment]
actually on all products!

**Comment by micahasmith** [comment]
screenshot me.

**Comment by gershonungar** [comment]
![capture5](https://cloud.githubusercontent.com/assets/15780728/11062834/f5915efa-87ba-11e5-82cf-8d153305a64a.PNG)
stuck on this page

**Comment by micahasmith** [comment]
any console errors?

do you have a url i could go to to inspect?

**Comment by gershonungar** [comment]
where can i send the url in private as it is not a public site yet

**Comment by micahasmith** [comment]
my email

**Comment by micahasmith** [comment]
for now allow localupload as well as an image option. you'll want to do this as it will be your customer's most popular image source (even for sites like yours)
