### ISSUE TITLE
Javascript error when using custom photo source

### ISSUE THREAD

**Issue by stephenoyoung** [printdotio/pio.js#104]
Using //az412349.vo.msecnd.net/pio/pio.latest.v2.js, after selecting an photo(s) and pressing the Continue button in the Customization screen we get the following javascript error:

Uncaught TypeError: p.localUpload.cancelUnfinishedUploads is not a functiononExit @ printio_widget.2.13.11447259296476.min.js.gzip:22onCompleteImageUploads @ printio_widget.2.13.11447259296476.min.js.gzip:22(anonymous function) @ printio_widget.2.13.11447259296476.min.js.gzip:13$.event.dispatch @ printio_widget.2.13.11447259296476.min.js.gzip:2g.handle.h @ printio_widget.2.13.11447259296476.min.js.gzip:2

We've set CanUserUploads = False in case that is a clue.

**Comment by micahasmith** [comment]
we have this bugfix releasing within the next 7 days. it happens when you have localupload = false (as you're noticing)

**Comment by micahasmith** [comment]
@stephenoyoung please retest-- should be fixed
