### ISSUE TITLE
Amazon S3 Signed URLs and Timeouts

### ISSUE THREAD

**Issue by jaidev** [printdotio/pio.js#105]
Currently we are using the web widget and passing in signed urls pointing to amazon s3. These signed urls as you know are valid for a period of time (currently we've set it at 15 min). Would there be a situation where the urls have timed out if the user took more than 15 min of time to create their photobook (for example) (OR) does print.io download these images in the background once the urls are supplied? Can you please confirm.

If these urls will indeed timeout, is there an optimal setting we should opt for to ensure that image urls are not timed out.

Thanks,
Jai

**Comment by micahasmith** [comment]
We don't download in the background. I would recommend upping your timeouts, or setting you bucket settings so that only HTTP Referrer header "print.io" has access -- another way to restrict

**Comment by jaidev** [comment]
thanks for the input
