### ISSUE TITLE
Altering the image url of items in cart at time of order

### ISSUE THREAD

**Issue by seancunningham** [printdotio/pio.js#108]
I was wondering if there is any support for updating the image urls at time of order, either using solely the widget or a combination of the widget and API. 

We currently use a signature method based around time expiry, and were hoping to update the urls at the time of order to ensure none are expired prior to sending the order.  I realize that, with a reasonable expiry time, this is not an issue unless the user leaves an item in the cart for a long period of time before committing to the order.

If not, are you aware of any standard solutions to integrating your widget into a website with private assets that do not require the image to be publicly available?

**Comment by seancunningham** [comment]
Linking the other thread, as it relates. I just wanted to create a new issue instead of hanging on to another. #95

**Comment by micahasmith** [comment]
moving to email ;)
