### ISSUE TITLE
Showing my image for printing

### ISSUE THREAD

**Issue by markneoglobal** [printdotio/pio.js#109]
I am using widget on my website. And i want to use printing. 
I have a image details page. I want to create a button here so when user click on PRINT THIS
it open up widget and show different print variations and prices. Here i have a link where i want this functionality 
http://www.neoglobal.etsollertis.com/artistic_artists/imagedetail/25

**Comment by micahasmith** [comment]
looks like it works to me! nice job.

what else do you need help with @markneoglobal ?

**Comment by jeffloth** [comment]
micah,
i am jeff who is working with nicole and your team to make this work.  she was showing me a site, and i am not sure which one it was, that can take images from my database and actually show them on your products and have them for sale from the catalog of items i have set up.  i need the image you see on the art detail page that mark showed you to have under it, a picture of your item for sale and our actual image on your item and then the end user can click on it and buy from your site, you handle all transaction for me.  that is what mark is trying to figure out how to do.  i know it can be done, a dynamic picture using our database from all our artists selling your products with their art on it.  can you help us do that?

**Comment by jeffloth** [comment]
i actually think i will loose sales if a customer can not see the products below art, i can't have the end user click a button that says print this.  the images with art from the same page need to be displayed so we can generate sales straight from a customer seeing it right on same page.  i hope you can understand what i am saying here and trying to get mark to do.  i am almost thinking that we need to build these items as ready to sell items through your site, but have them be dynamic so for each piece of art for sale all the images change to be the same as the art on the top of my page when it loads.

**Comment by micahasmith** [comment]
@jeffloth i get it. i believe you want to look at our productpreview API (and not at the widget), but i could have mis-read.

the docs for that are -> https://api.print.io/docs/#!/productpreview/POST_post_0

since this is more advanced, let me know if you want to do a call to discuss. micah at gooten dott com

**Comment by jeffloth** [comment]
can you help mark figure this out with our site?

**Comment by micahasmith** [comment]
@jeffloth sure. email me and lets do a call

**Comment by jeffloth** [comment]
i need you to get on skype with mark.  i have paid his team to build me the site.  i really would like this to work with you guys.  he and you will figure it out i am sure.  i will email him and tell him you want to chat.
thank you so much for helping to make this work between us.
jeff

**Comment by jeffloth** [comment]
what times are you available for to do a skype call with my team?  and what time zone are you?

**Comment by jeffloth** [comment]
my team is trying to set up a time for them and you to talk and see if you can quickly help them straighten out how to display our art correctly so we can start to sell through your site.  the soonest you can set up a time with them they will be there for it.

**Comment by micahasmith** [comment]
@jeffloth my first available is wednesday at 5PM EST, does that work for you?

**Comment by jeffloth** [comment]
I will let them know.  boy, you are busy.  i will get back to you.

**Comment by jeffloth** [comment]
ok. that works

**Comment by jeffloth** [comment]
![2016_04_11_16_37_130001](https://cloud.githubusercontent.com/assets/18297807/14443351/44ea595e-0004-11e6-8ba2-70989d3964e4.jpg)

mark and micah, this is what i am driving at doing with the art site.  i drew it up a bit so it would be easier for everyone to see.  

so if you have this artwork, http://artisticartists.com/imagedetail/365, and then under it the same artwork will load in real time on the page with prints, canvases and so forth ready to sell in rows under the piece of artwork with that exact same image on the pieces for sale.  then all transactions go through micah's site for us, from ordering to shipping.  i have it all set up on his site under artistic artists.  i hope this makes more sense now with the picture for what we need to do.
jeff

**Comment by jeffloth** [comment]
what is your name on skype so i can get it to the guys so they are ready on wednesday

**Comment by jeffloth** [comment]
micah, the skype names for each of us are, mark.neoglobal, neo.global, and mine is artisticartists
if you could add these so we are ready on wednesday for you to go over everything, that would be great.  jeff

**Comment by jeffloth** [comment]
micah, we have everyone on skype and not you. are you still going to help us out today?
