### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by sebnun** [printdotio/pio.js#111]
Hi, I followed the documentation of the javascript SDK, I'm not sure what I'm doing wrong but I can't customize the widget with css.

this is my code:

```
<html>
<head>

</head>
<body>

 <div id="container"></div>

<script src="https://az412349.vo.msecnd.net/pio/pio.latest.v2.js"></script>

<script>

var el = document.getElementById('container');

PIO.config({

recipeId:"(my live recipe Id)",
url:"https://widget.print.io/widget/",
embedInElement:el,

style: {
showHeader: true,
cssUrl:'/custom.css'
},

iframeStyles:{
        width:"100%"
}

});

PIO.open();

</script>

</body>
</html>

```

I tried with `cssUrl:'custom.css'` and `cssUrl:'http://picsirl.rocks/custom.css'` but it doesn't seems to load the css file.

My intention is to have the widget with width and height 100% of the page, not in a popup + custom css.
Thanks.

**Comment by micahasmith** [comment]
do you have a url that supports https to try it on?

**Comment by sebnun** [comment]
no, only http

**Comment by micahasmith** [comment]
What sort of web server do you run on your localhost

**Comment by sebnun** [comment]
I'm testing the widget on hostgator on http://picsirl.rocks , they use apache
the custom css is in http://picsirl.rocks/custom.css

I'm fairly new to javascript, does the widget have to be on an https site to work?

**Comment by micahasmith** [comment]
you want it on https, especially b/c users enter credit card info in the widget, and that just looks shady w/o https.

but the css issue is all https.

![image](https://cloud.githubusercontent.com/assets/959902/17515019/ebe75132-5e03-11e6-9507-fac3174b5b2d.png)
