### ISSUE TITLE
Ability to create multiple users with restrictions

### ISSUE THREAD

**Issue by carterteefury** [printdotio/pio.js#74]
As an account admin, I want to be able to create multiple users and give them specific permissions, so that certain users cannot see or modify account and payment settings.

**Comment by mrgreenfur** [comment]
@carterteefury Great idea. How about just two roles: Admin (full access) and Viewer (Everything but account settings, e.g. orders, coupons, reports, dashboard, etc.)?

**Comment by carterteefury** [comment]
Yeah I think that would work as an mvp. But like I told Austen, ultimately, giving users permissions to read/write and which screens they can do so, would be great. Also, if the user can't see settings, why should they see financials? Just some things to consider moving forward.

Our Customer Service reps don't need to see our cost, or what we owe print.io, or anything like that. It's not that we don't want to be transparent, it's that they don't need that information to do their job so why give it to them. But they do need to be able to see where in the production process the order is at, in case a customer asks.

**Comment by mrgreenfur** [comment]
@carterteefury Makes sense. Did you have roles in mind other than 'Customer Service Rep'?

**Comment by carterteefury** [comment]
The only other role would be accounting, but the Viewer role you mentioned would be perfect for that one!

**Comment by bhox** [comment]
@carterteefury we are building this feature out now. Could we hop on the phone/ google hangout and I can show you where we're going? I'd love your feedback.

**Comment by bhox** [comment]
Live
