### ISSUE TITLE
Does "fadeBackground: false" still have any effect?

### ISSUE THREAD

**Issue by ocram** [printdotio/pio.js#76]
In your [docs](http://print.io/platform-web-customization), you describe that one can use `fadeBackground: true` to "turn off the black background".

But we can't see any effect. Could you clarify whether this does still work and where we can see the effect of this setting?

**Comment by bhox** [comment]
Investigating

**Comment by bhox** [comment]
It seems to work okay to hide the lightbox in the example in page: http://print.io/platform-web-customization

**Comment by ocram** [comment]
Thank you! So this does only affect the lightbox/fancybox? I'm using the `embedInElement: element` property and was wondering what background this refers to.

**Comment by bhox** [comment]
Yeah, it doesn't do anything if the widget is embedded since there is no light/fancybox to hide. Is there an effect you were working on that I can help with?

**Comment by ocram** [comment]
No, that's fine. I was just wondering.

I'm going to close this issue as my question has been answered. Maybe you should add this piece of context to your documentation, i.e. that this affects the lightbox/fancybox.

**Comment by bhox** [comment]
Great feedback, will add the clarification, thanks!
