### ISSUE TITLE
bug(staging): cors failure

### ISSUE THREAD

**Issue by mfo** [printdotio/pio.js#85]
When I open my staging widget in HTTP_S_, it fails to load my products form your APIs (the view is loaded/rendered, but a call to your API fails'

A few more info :
- _iframe src_ : https://staging.widget.print.io/widget/fr/en/secretReceipeId
- surprisingly, the iframe is redirected to : /widget/fr/en/secretReceipeId (I'm located in France, with a browser in English ; maybe it's the root cause of this redirection)
- the pio.js iframe instanciate the widget, render the layout, try to load your product :
  `XMLHttpRequest cannot load http://staging.widget.print.io/api/v/1/source/widget/products?recipeid=xxx&countryCode=FR&languageCode=en&currencyCode=EUR. Invalid HTTP status code 405`
- and fails

Feel free to contact me via mail(fourcade.m+piojs@gmail.com)/skype(fourcade.martin) if you need more info.

Best regards,
mfo

**Comment by bhox** [comment]
Hey @mfo ,
It seems we have a broken cert on staging which is probably causing this problem. Do you have a testing/staging site you can share so we can see your setup?

**Comment by mfo** [comment]
@benhoxie I just answered your question by mail

**Comment by mfo** [comment]
also, regarding the root cause of the issue, I felt that it's about a cors method not allowed (OPTIONS)
