### ISSUE TITLE
Credit Card Number for testing on staging?

### ISSUE THREAD

**Issue by terhechte** [printdotio/pio.js#87]
Hey,

what credit card number can I use for testing the staging? I've always used 
4242424242424242    Visa

However, when I do that, I get a javascript error in pio.js and it never returns sucessfully. Which number can I use to successfully test payment on staging?

Cheers,
Benedikt

**Comment by micahasmith** [comment]
4111111111111111

**Comment by terhechte** [comment]
Thanks, worked like a charm
