### ISSUE TITLE
SSL Certs Not Trusted on Staging

### ISSUE THREAD

**Issue by nicholasdunbar** [printdotio/pio.js#93]
Hi @benhoxie @printioengineering and @thetriciarussel (Tricia Russel). I am from the partnering company (6 Genius Incorporated) and I was told to contact you via GitHub by Tijana Evstratiev.

I'm having an issue in staging where Firefox is blocking the requests because the SSL certs are not from a trusted source. Here is the reproduction case:

1.) Configure pio.js and open it inside of an iframe

``` javascript
PIO.config({
            // required -- api key
            recipeId:"blblblblblblaaablblaba",
            //REQUIRED
            // url of widget (can be staging or live)
            url: 'https://staging.widget.print.io/widget/'

        });
        drawingPath = 'https://sketchnpass.com/images/poopMan.jpg';
        PIO.open({
             images:[drawingPath]
        });
```

2.) Run code in Firefox 38.0.5 in an iframe

**Expected Result:**
Widget loads
**Actual Result:**
the grey div with id="__pio_f" is added to DOM but the pio iframe is invisible.

3.) go to widget url (https://staging.widget.print.io/widget/) directly by pasting the url into the browser address bar.

**Result:**
Connection Untrusted (you know this thing --> https://support.mozilla.org/en-US/kb/connection-untrusted-error-message)

4.) add exception to firefox to bypass the ssl warning
5.) Run pio initialization code from step 1 in iframe again

**Result:** 
Widget loads and loading screen comes up

6.) Wait for product page to load

**Expected Result:**
The list of products would normally appear on the categories page
**Actual Result:**
loading wheel just runs on the categories page. The product list never loads.
![print-io-loading-screen](https://cloud.githubusercontent.com/assets/6301491/8242503/0a4757ba-15cd-11e5-9921-7ed4bf83c00f.png)

Firefox complains of the following:
![firefox is blocking](https://cloud.githubusercontent.com/assets/6301491/8242470/b58b6766-15cc-11e5-9559-6ba2fcc6a35c.png)

Thank you for your help in advance

**Comment by micahasmith** [comment]
we have a fix for this in the works-- hoping to get it out next week.

for now, and as a temp fix until we get that, you can set the url like so:

```
PIO.config({
  url:"https://bowser.print.io/widget/"
});
```

**Comment by nicholasdunbar** [comment]
Thank you

**Comment by micahasmith** [comment]
this has been fixed-- can use 'https://staging-widget.print.io/widget/'
