### ISSUE TITLE
Acrylic Block product preview 

### ISSUE THREAD

**Issue by dgquint** [printdotio/pio.js#97]
Early on in the process, the 6 photo collage option shows black piping and later on it shows white piping. See attached photos.
<img width="205" alt="screen shot 2015-09-22 at 10 44 10 am" src="https://cloud.githubusercontent.com/assets/14790359/10023910/70dedf16-6122-11e5-9e18-b1cf9a8132d1.png">
<img width="860" alt="screen shot 2015-09-22 at 10 44 27 am" src="https://cloud.githubusercontent.com/assets/14790359/10023909/70dea9ba-6122-11e5-8521-cacdcc9a74a6.png">

**Comment by TheTriciaRussel** [comment]
@benhoxie  bug or issue with templates?

**Comment by bhox** [comment]
@dgquint It seems that template actually renders a black background. We will update it so that it shows black on the edit page shortly.

**Comment by dgquint** [comment]
@benhoxie see you closed this out but still seeing the white on the edit page.
